# Copyright (c) OSO DevOps
# SPDX-License-Identifier: MPL-2.0

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10
